name: gemini_app
description: "Khamilia diary app."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  lottie: ^3.1.2
  cloud_firestore: ^4.17.5
  syncfusion_flutter_charts: ^27.1.50
  localstorage: ^5.0.0
  flutter_native_splash: ^2.4.1
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  google_generative_ai: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - lib/images/
    - lib/assets/