// import 'dart:io';
// GARBAGE
// import 'package:google_generative_ai/google_generative_ai.dart';

// void main() async {
//   final apiKey = Platform.environment['GEMINI_API_KEY'];
//   if (apiKey == null) {
//     stderr.writeln(r'No $GEMINI_API_KEY environment variable');
//     exit(1);
//   }

//   final model = GenerativeModel(
//     model: 'gemini-1.5-flash',
//     apiKey: apiKey,
//     // safetySettings: Adjust safety settings
//     // See https://ai.google.dev/gemini-api/docs/safety-settings
//     generationConfig: GenerationConfig(
//       temperature: 1,
//       topK: 64,
//       topP: 0.95,
//       maxOutputTokens: 8192,
//       responseMimeType: 'text/plain',
//     ),
//   );

//   final response = await model.generateContent([
//     TextPart('You are a called kali or ka, you can perform only perform the following tasks:\n- if the input is a mp3 format first convert the audio to text and then on the text perform the following:\n- if the text is about a description of a day \n- if the the text is asking to group together a list of activities\n- if the text is a query or question create a query\n- if the text is a for setting a notification\n- if the text is a for setting a periodic activity\n- if the text is a to categorize a list of emotions\n- else respond that it is not possible to perform the action'),
//     TextPart('input: Hey Kali, I woke up early, went for a jog, and had a healthy breakfast. Now I\'m tackling my to-do list.'),
//     TextPart('output: {"type":"activities", "data": [jogging, breakfast, work]}'),
//     TextPart('input: Hey Kali, it\'s been a quiet day of reading, catching up on emails, and baking something delicious'),
//     TextPart('output: {"type":"activities", "data": [reading, emails, baking]}'),
//     TextPart('input: Hey Kali, the day was filled with errands - groceries, the bank, and picking up a birthday present'),
//     TextPart('output: {"type":"activities", "data": [groceries, bank, birthday shopping]}'),
//     TextPart('input: Hey Kali, I spent the afternoon at the park with my kids, playing frisbee and chasing butterflies'),
//     TextPart('output: {"type":"activities", "data": [frisbee, park, playing]}'),
//     TextPart('input: Hey Kali, I\'m currently in a yoga class, working on my flexibility and inner peace'),
//     TextPart('output: {"type":"activities", "data": [yoga]}'),
//     TextPart('input: Hey Kali, I spent the morning volunteering at the animal shelter, petting fluffy kittens and playing with playful pups'),
//     TextPart('output: {"type":"activities", "data": [volunteering, petting kittens, playing with pups]}'),
//     TextPart('input: Hey Kali, I went on a hike with my dog, enjoying the fresh air and scenic views'),
//     TextPart('output: {"type":"activities", "data": [hiking, dog walk, nature]}'),
//     TextPart('input: Hey Kali, I\'m working on a big project at the library, surrounded by books and quiet concentration'),
//     TextPart('output: {"type":"activities", "data": [library, project, studying]}'),
//     TextPart('input: Hey Kali, I had a productive day of writing, editing, and brainstorming new ideas'),
//     TextPart('output: {"type":"activities", "data": [writing, editing, brainstorming]}'),
//     TextPart('input: Hey Kali, I spent the evening at a movie theatre, laughing and enjoying the latest blockbuster'),
//     TextPart('output: {"type":"activities", "data": [movie]}'),
//     TextPart('input: Hey Kali, I\'m at home, catching up on some much-needed rest and relaxation'),
//     TextPart('output: {"type":"activities", "data": [relaxation, rest]}'),
//     TextPart('input: Hey Kali, I spent the day exploring a new city, trying delicious food and admiring the architecture'),
//     TextPart('output: {"type":"activities", "data": [exploring, food, architecture]}'),
//     TextPart('input: Hey Kali, I had a busy day at the office, finishing presentations and collaborating with my team'),
//     TextPart('output: {"type":"activities", "data": [work, presentations, meetings]}'),
//     TextPart('input: Hey Kali, I\'m currently at a coffee shop, enjoying a latte and getting some work done'),
//     TextPart('output: {"type":"activities", "data": [coffee, work]}'),
//     TextPart('input: Hey Kali, I went to a museum and learned about ancient civilizations. It was fascinating!'),
//     TextPart('output: {"type":"activities", "data": [museum, history]}'),
//     TextPart('input: Hey Kali, I had a lovely lunch with my family, catching up and sharing stories'),
//     TextPart('output: {"type":"activities", "data": [family lunch, catching up]}'),
//     TextPart('input: Hey Kali, I spent the day gardening, planting flowers and tending to my vegetables'),
//     TextPart('output: {"type":"activities", "data": [gardening, planting, veggies]}'),
//     TextPart('input: Hey Kali, I\'m learning a new skill online, expanding my knowledge and horizons'),
//     TextPart('output: {"type":"activities", "data": [online learning]}'),
//     TextPart('input: Hey Kali, I had a relaxing evening at home, reading a good book and listening to music'),
//     TextPart('output: {"type":"activities", "data": [reading, music, relaxing]}'),
//     TextPart('input: Hey Kali, I went to a concert tonight, enjoying the live music and energy of the crowd'),
//     TextPart('output: {"type":"activities", "data": [concert, live music]}'),
//     TextPart('input: Hey Kali, I\'m at a restaurant, celebrating a friend\'s birthday with delicious food and drinks'),
//     TextPart('output: {"type":"activities", "data": [birthday dinner, celebrating]}'),
//     TextPart('input: Hey Kali, I spent the morning cleaning and organizing my house, making it feel fresh and welcoming'),
//     TextPart('output: {"type":"activities", "data": [cleaning, organizing, housework]}'),
//     TextPart('input: Hey Kali, I took a bike ride through the park, enjoying the sunshine and fresh air'),
//     TextPart('output: {"type":"activities", "data": [bike ride, park, sunshine]}'),
//     TextPart('input: Hey Kali, I spent the day at the beach, soaking up the sun and swimming in the waves'),
//     TextPart('output: {"type":"activities", "data": [beach, swimming, sun]}'),
//     TextPart('input: Hey Kali, I\'m at a sporting event, cheering on my favorite team with excitement and passion'),
//     TextPart('output: {"type":"activities", "data": [sports, cheering]}'),
//     TextPart('input: Hey Kali, I had a productive day at work, completing tasks and achieving my goals'),
//     TextPart('output: {"type":"activities", "data": [work, tasks, achieving goals]}'),
//     TextPart('input: Hey Kali, I spent the evening cooking a delicious meal, experimenting with new flavors and ingredients'),
//     TextPart('output: {"type":"activities", "data": [cooking, meal prep]}'),
//     TextPart('input: Hey Kali, I\'m at the gym, working out and taking care of my physical health'),
//     TextPart('output: {"type":"activities", "data": [gym, workout]}'),
//     TextPart('input: Hey Kali, I spent the day at a local market, buying fresh produce and supporting small businesses'),
//     TextPart('output: {"type":"activities", "data": [market, shopping, supporting local]}'),
//     TextPart('input: Hey Kali, I had a relaxing day at a spa, getting a massage and pampering myself'),
//     TextPart('output: {"type":"activities", "data": [spa, pampering, massage]}'),
//     TextPart('input: Hey Kali, I\'m at a conference, learning from experts and networking with professionals'),
//     TextPart('output: {"type":"activities", "data": [conference, learning, networking]}'),
//     TextPart('input: Hey Kali, I had a great day with friends, going out for dinner and having lots of laughs'),
//     TextPart('output: {"type":"activities", "data": [dinner, friends, laughs]}'),
//     TextPart('input: Hey Kali, I spent the day at a theme park, riding roller coasters and enjoying the rides'),
//     TextPart('output: {"type":"activities", "data": [theme park, roller coasters]}'),
//     TextPart('input: Hey Kali, I\'m attending a workshop, learning new skills and expanding my knowledge'),
//     TextPart('output: {"type":"activities", "data": [workshop, learning, new skills]}'),
//     TextPart('input: Hey Kali, I had a quiet day at home, catching up on some reading and enjoying a cup of tea'),
//     TextPart('output: {"type":"activities", "data": [reading, tea, relaxing]}'),
//     TextPart('input: Hey Kali, I went to a play tonight, enjoying the performance and the stories it told'),
//     TextPart('output: {"type":"activities", "data": [play, theater]}'),
//     TextPart('input: Hey Kali, I spent the day working on a creative project, using my imagination and skills'),
//     TextPart('output: {"type":"activities", "data": [creative project]}'),
//     TextPart('input: Hey Kali, I\'m at a party, celebrating with friends and family'),
//     TextPart('output: {"type":"activities", "data": [party, celebrating]}'),
//     TextPart('input: Hey Kali, I had a fulfilling day, volunteering my time and making a difference'),
//     TextPart('output: {"type":"activities", "data": [volunteering]}'),
//     TextPart('input: Hey Kali, I went on a date tonight, enjoying a romantic evening with someone special'),
//     TextPart('output: {"type":"activities", "data": [date, romance]}'),
//     TextPart('input: Hey Kali, I\'m currently at a concert, enjoying the music and the atmosphere'),
//     TextPart('output: {"type":"activities", "data": [concert, music]}'),
//     TextPart('input: Hey Kali, I spent the day learning a new language, expanding my horizons and communication skills'),
//     TextPart('output: {"type":"activities", "data": [language learning]}'),
//     TextPart('input: Hey Kali, I had a successful day at work, meeting deadlines and achieving goals'),
//     TextPart('output: {"type":"activities", "data": [work, deadlines, goals]}'),
//     TextPart('input: Hey Kali, I went to a poetry reading tonight, appreciating the beauty of language and expression'),
//     TextPart('output: {"type":"activities", "data": [poetry reading]}'),
//     TextPart('input: Hey Kali, I\'m at a coffee shop, enjoying a cup of coffee and working on my laptop'),
//     TextPart('output: {"type":"activities", "data": [coffee, work]}'),
//     TextPart('input: Hey Kali, I spent the day exploring a new part of my city, discovering hidden gems and local treasures'),
//     TextPart('output: {"type":"activities", "data": [exploring, local gems]}'),
//     TextPart('input: Hey Kali, I had a productive day, working on personal projects and making progress towards my goals'),
//     TextPart('output: {"type":"activities", "data": [personal projects, goals]}'),
//     TextPart('input: Hey Kali, I\'m currently at a book signing, meeting my favorite author and getting my book signed'),
//     TextPart('output: {"type":"activities", "data": [book signing, author]}'),
//     TextPart('input: Hey Kali, I had a fulfilling day, filled with small joys and moments of happiness'),
//     TextPart('output: {"type":"activities", "data": [happiness, joy]}'),
//     TextPart('input: Hey Kali, I spent the day at the zoo, admiring the animals and learning about conservation efforts'),
//     TextPart('output: {"type":"activities", "data": [zoo, animals, conservation]}'),
//     TextPart('input: Group together the following acitivies: [yoga, grocery shopping, dinner with friends] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "yoga" ],"Entertainment": [],"Learning & development": [],"work & chores": [ "grocery shopping" ],"Social & Personal": [ "dinner with friends" ]}'),
//     TextPart('input: Group together the following acitivies: [running errands, reading a book, catching up with family] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [],"Entertainment": [ "reading a book" ],"Learning & development": [],"work & chores": [ "running errands" ],"Social & Personal": [ "catching up with family" ]}'),
//     TextPart('input: Group together the following acitivies: [attending a conference, working on a presentation, going to a concert] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [],"Entertainment": [ "going to a concert" ],"Learning & development": [ "attending a conference" ],"work & chores": [ "working on a presentation" ],"Social & Personal": []}'),
//     TextPart('input: Group together the following acitivies: [cleaning the house, hiking, writing a blog post] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "hiking" ],"Entertainment": [],"Learning & development": [ "writing a blog post" ],"work & chores": [ "cleaning the house" ],"Social & Personal": []}'),
//     TextPart('input: Group together the following acitivies: [cooking dinner, playing board games, volunteering at a shelter] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [],"Entertainment": [ "playing board games" ],"Learning & development": [],"work & chores": [ "cooking dinner" ],"Social & Personal": [ "volunteering at a shelter"]}'),
//     TextPart('input: Group together the following acitivies: [going to the gym, attending a workshop, spending time with a friend] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the gym" ], "Entertainment": [], "Learning & development": [ "attending a workshop" ], "work & chores": [], "Social & Personal": [ "spending time with a friend"  ] }'),
//     TextPart('input: Group together the following acitivies: [working on a project, reading a magazine, catching up on emails] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "reading a magazine" ], "Learning & development": [], "work & chores": [ "working on a project", "catching up on emails" ], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [going to the movies, baking a cake, attending a birthday party] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "going to the movies", "baking a cake" ], "Learning & development": [], "work & chores": [], "Social & Personal": [ "attending a birthday party"  ] }'),
//     TextPart('input: Group together the following acitivies: [learning a new language, taking a walk, having a coffee date] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "taking a walk" ], "Entertainment": [], "Learning & development": [ "learning a new language" ], "work & chores": [], "Social & Personal": [ "having a coffee date"  ] }'),
//     TextPart('input: Group together the following acitivies: [doing laundry, going to the theater, having dinner with family] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "going to the theater" ], "Learning & development": [], "work & chores": [ "doing laundry" ], "Social & Personal": [ "having dinner with family"  ] }'),
//     TextPart('input: Group together the following acitivies: [working from home, going for a run, reading a novel] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going for a run" ], "Entertainment": [ "reading a novel" ], "Learning & development": [], "work & chores": [ "working from home" ], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [gardening, attending a concert, taking a yoga class] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "gardening", "taking a yoga class" ], "Entertainment": [ "attending a concert" ], "Learning & development": [], "work & chores": [], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [preparing for a presentation, playing video games, catching up with friends] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "playing video games" ], "Learning & development": [], "work & chores": [ "preparing for a presentation" ], "Social & Personal": [ "catching up with friends"  ] }'),
//     TextPart('input: Group together the following acitivies: [going to the library, taking a bike ride, volunteering at a food bank] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "taking a bike ride" ], "Entertainment": [], "Learning & development": [ "going to the library" ], "work & chores": [], "Social & Personal": [ "volunteering at a food bank"  ] }'),
//     TextPart('input: Group together the following acitivies: [cleaning the kitchen, watching a movie, having a picnic] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "watching a movie", "having a picnic" ], "Learning & development": [], "work & chores": [ "cleaning the kitchen" ], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [working on a side hustle, going for a walk, having a coffee date] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going for a walk" ], "Entertainment": [], "Learning & development": [], "work & chores": [ "working on a side hustle" ], "Social & Personal": [ "having a coffee date"  ] }'),
//     TextPart('input: Group together the following acitivies: [going to the gym, attending a poetry reading, spending time with family] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the gym" ], "Entertainment": [ "attending a poetry reading" ], "Learning & development": [], "work & chores": [], "Social & Personal": [ "spending time with family"  ] }'),
//     TextPart('input: Group together the following acitivies: [cooking a healthy meal, learning a new skill, going out with friends] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [], "Learning & development": [ "learning a new skill" ], "work & chores": [ "cooking a healthy meal" ], "Social & Personal": [ "going out with friends"  ] }'),
//     TextPart('input: Group together the following acitivies: [working on a presentation, going for a hike, having a movie night] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going for a hike" ], "Entertainment": [ "having a movie night" ], "Learning & development": [], "work & chores": [ "working on a presentation" ], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [attending a networking event, going to the beach, reading a book] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the beach" ], "Entertainment": [ "reading a book" ], "Learning & development": [], "work & chores": [], "Social & Personal": [ "attending a networking event"  ] }'),
//     TextPart('input: Group together the following acitivies: [doing laundry, going to a museum, having dinner with a loved one] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "going to a museum" ], "Learning & development": [], "work & chores": [ "doing laundry" ], "Social & Personal": [ "having dinner with a loved one"  ] }'),
//     TextPart('input: Group together the following acitivies: [working on a project, playing video games, going for a jog] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going for a jog" ], "Entertainment": [ "playing video games" ], "Learning & development": [], "work & chores": [ "working on a project" ], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [going to the gym, attending a workshop, having coffee with a friend] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the gym" ], "Entertainment": [], "Learning & development": [ "attending a workshop" ], "work & chores": [], "Social & Personal": [ "having coffee with a friend"  ] }'),
//     TextPart('input: Group together the following acitivies: [cleaning the house, watching a movie, spending time with family] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "watching a movie" ], "Learning & development": [], "work & chores": [ "cleaning the house" ], "Social & Personal": [ "spending time with family"  ] }'),
//     TextPart('input: Group together the following acitivies: [going to the library, attending a concert, having a picnic] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "attending a concert", "having a picnic" ], "Learning & development": [ "going to the library" ], "work & chores": [], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [working on a side hustle, going for a walk, volunteering at a local charity] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going for a walk" ], "Entertainment": [], "Learning & development": [], "work & chores": [ "working on a side hustle" ], "Social & Personal": [ "volunteering at a local charity"  ] }'),
//     TextPart('input: Group together the following acitivies: [taking a dance class, cooking a meal, catching up with friends] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "taking a dance class" ], "Entertainment": [], "Learning & development": [], "work & chores": [ "cooking a meal" ], "Social & Personal": [ "catching up with friends"  ] }'),
//     TextPart('input: Group together the following acitivies: [working on a presentation, going to the beach, having a dinner party] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the beach" ], "Entertainment": [], "Learning & development": [], "work & chores": [ "working on a presentation" ], "Social & Personal": [ "having a dinner party"  ] }'),
//     TextPart('input: Group together the following acitivies: [going to the gym, attending a book club meeting, spending time with loved ones] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the gym" ], "Entertainment": [], "Learning & development": [ "attending a book club meeting" ], "work & chores": [], "Social & Personal": [ "spending time with loved ones"  ] }'),
//     TextPart('input: Group together the following acitivies: [learning a new skill, taking a hike, going out for a night out] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "taking a hike" ], "Entertainment": [], "Learning & development": [ "learning a new skill" ], "work & chores": [], "Social & Personal": [ "going out for a night out"  ] }'),
//     TextPart('input: Group together the following acitivies: [working on a project, playing board games, having a coffee date] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "playing board games" ], "Learning & development": [], "work & chores": [ "working on a project" ], "Social & Personal": [ "having a coffee date"  ] }'),
//     TextPart('input: Group together the following acitivies: [going to the library, attending a concert, spending time with family] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "attending a concert" ], "Learning & development": [ "going to the library" ], "work & chores": [], "Social & Personal": [ "spending time with family"  ] }'),
//     TextPart('input: Group together the following acitivies: [working from home, going for a run, reading a magazine] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going for a run" ], "Entertainment": [ "reading a magazine" ], "Learning & development": [], "work & chores": [ "working from home" ], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [cleaning the house, going to a museum, having dinner with friends] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "going to a museum" ], "Learning & development": [], "work & chores": [ "cleaning the house" ], "Social & Personal": [ "having dinner with friends"  ] }'),
//     TextPart('input: Group together the following acitivies: [taking a yoga class, attending a play, spending time with a loved one] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "taking a yoga class" ], "Entertainment": [ "attending a play" ], "Learning & development": [], "work & chores": [], "Social & Personal": [ "spending time with a loved one"  ] }'),
//     TextPart('input: Group together the following acitivies: [working on a project, playing video games, going for a walk] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going for a walk" ], "Entertainment": [ "playing video games" ], "Learning & development": [], "work & chores": [ "working on a project" ], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [going to the gym, attending a workshop, catching up with friends] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the gym" ], "Entertainment": [], "Learning & development": [ "attending a workshop" ], "work & chores": [], "Social & Personal": [ "catching up with friends"  ] }'),
//     TextPart('input: Group together the following acitivies: [cooking a meal, reading a book, having a coffee date] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "reading a book" ], "Learning & development": [], "work & chores": [ "cooking a meal" ], "Social & Personal": [ "having a coffee date"  ] }'),
//     TextPart('input: Group together the following acitivies: [working on a presentation, going to the beach, spending time with family] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the beach" ], "Entertainment": [], "Learning & development": [], "work & chores": [ "working on a presentation" ], "Social & Personal": [ "spending time with family"  ] }'),
//     TextPart('input: Group together the following acitivies: [going to the gym, attending a concert, having dinner with a loved one] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the gym" ], "Entertainment": [ "attending a concert" ], "Learning & development": [], "work & chores": [], "Social & Personal": [ "having dinner with a loved one"  ] }'),
//     TextPart('input: Group together the following acitivies: [learning a new skill, taking a hike, going out for a night out] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "taking a hike" ], "Entertainment": [], "Learning & development": [ "learning a new skill" ], "work & chores": [], "Social & Personal": [ "going out for a night out"  ] }'),
//     TextPart('input: Group together the following acitivies: [working on a project, playing board games, having coffee with a friend] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "playing board games" ], "Learning & development": [], "work & chores": [ "working on a project" ], "Social & Personal": [ "having coffee with a friend"  ] }'),
//     TextPart('input: Group together the following acitivies: [going to the library, attending a concert, spending time with family] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "attending a concert" ], "Learning & development": [ "going to the library" ], "work & chores": [], "Social & Personal": [ "spending time with family"  ] }'),
//     TextPart('input: Group together the following acitivies: [working from home, going for a run, reading a magazine] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going for a run" ], "Entertainment": [ "reading a magazine" ], "Learning & development": [], "work & chores": [ "working from home" ], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [cleaning the house, going to a museum, having dinner with friends] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [], "Entertainment": [ "going to a museum" ], "Learning & development": [], "work & chores": [ "cleaning the house" ], "Social & Personal": [ "having dinner with friends"  ] }'),
//     TextPart('input: Group together the following acitivies: [taking a yoga class, attending a play, spending time with a loved one] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "taking a yoga class" ], "Entertainment": [ "attending a play" ], "Learning & development": [], "work & chores": [], "Social & Personal": [ "spending time with a loved one"  ] }'),
//     TextPart('input: Group together the following acitivies: [working on a project, playing video games, going for a walk] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going for a walk" ], "Entertainment": [ "playing video games" ], "Learning & development": [], "work & chores": [ "working on a project" ], "Social & Personal": [ ] }'),
//     TextPart('input: Group together the following acitivies: [going to the gym, attending a workshop, catching up with friends] in these 5 categories: [Physical Activities,Entertainment,Learning & development, work & chores, Social & Personal]'),
//     TextPart('output: {"type":"group", "Physical Activities": [ "going to the gym" ], "Entertainment": [], "Learning & development": [ "attending a workshop" ], "work & chores": [], "Social & Personal": [ "catching up with friends"  ] }'),
//     TextPart('input: Get all sales transactions for October 26th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-10-26 ", "end": "2023-10-26"}'),
//     TextPart('input: Retrieve customer support tickets submitted on New Year\'s Day, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-01-01 ", "end": "2024-01-01"}'),
//     TextPart('input: Show me the website traffic data for September 15th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-09-15 ", "end": "2023-09-15"}'),
//     TextPart('input: What were the website orders placed on Christmas Eve 2023?'),
//     TextPart('output: {"type": "query", "start": "2023-12-24 ", "end": "2023-12-24"}'),
//     TextPart('input: List all employee attendance records for August 10th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-08-10 ", "end": "2023-08-10"}'),
//     TextPart('input: Get the number of new users registered on November 11th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-11-11 ", "end": "2023-11-11"}'),
//     TextPart('input: Show me the sales figures for Valentine\'s Day, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-02-14 ", "end": "2024-02-14"}'),
//     TextPart('input: Retrieve the customer feedback collected on Independence Day, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-07-04 ", "end": "2023-07-04"}'),
//     TextPart('input: Get the website analytics for May 1st, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-05-01 ", "end": "2023-05-01"}'),
//     TextPart('input: Show me the number of active users on Halloween, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-10-31 ", "end": "2023-10-31"}'),
//     TextPart('input: What was the total revenue generated on St. Patrick\'s Day, 2024?'),
//     TextPart('output: {"type": "query", "start": "2024-03-17 ", "end": "2024-03-17"}'),
//     TextPart('input: Get the customer service interactions on June 15th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-06-15 ", "end": "2023-06-15"}'),
//     TextPart('input: Show me the marketing campaign performance for April 1st, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-04-01 ", "end": "2023-04-01"}'),
//     TextPart('input: Retrieve the product inventory levels for September 22nd, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-09-22 ", "end": "2023-09-22"}'),
//     TextPart('input: What were the website orders placed on Easter Sunday, 2024?'),
//     TextPart('output: {"type": "query", "start": "2024-04-21 ", "end": "2024-04-21"}'),
//     TextPart('input: Get the number of new leads generated on March 8th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-03-08 ", "end": "2023-03-08"}'),
//     TextPart('input: Show me the website traffic data for New Year\'s Eve, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-12-31 ", "end": "2023-12-31"}'),
//     TextPart('input: Retrieve the customer support tickets submitted on October 12th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-10-12 ", "end": "2023-10-12"}'),
//     TextPart('input: What were the sales figures for Memorial Day, 2024?'),
//     TextPart('output: {"type": "query", "start": "2024-05-27 ", "end": "2024-05-27"}'),
//     TextPart('input: Get the website analytics for January 15th, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-01-15 ", "end": "2024-01-15"}'),
//     TextPart('input: Show me the number of active users on August 21st, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-08-21 ", "end": "2023-08-21"}'),
//     TextPart('input: What was the total revenue generated on Black Friday, 2023?'),
//     TextPart('output: {"type": "query", "start": "2023-11-23 ", "end": "2023-11-23"}'),
//     TextPart('input: Get the customer service interactions on June 19th, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-06-19 ", "end": "2024-06-19"}'),
//     TextPart('input: Show me the marketing campaign performance for February 2nd, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-02-02 ", "end": "2024-02-02"}'),
//     TextPart('input: Retrieve the product inventory levels for July 14th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-07-14 ", "end": "2023-07-14"}'),
//     TextPart('input: What were the website orders placed on Good Friday, 2024?'),
//     TextPart('output: {"type": "query", "start": "2024-04-05 ", "end": "2024-04-05"}'),
//     TextPart('input: Get all sales transactions from January 1st, 2023 to December 31st, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-01-01", "end": "2023-12-31" }'),
//     TextPart('input: Retrieve customer support tickets submitted between March 15th, 2024 and April 15th, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-03-15", "end": "2024-04-15" }'),
//     TextPart('input: Show me the website traffic data for the month of June 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-06-01", "end": "2023-06-30" }'),
//     TextPart('input: What were the website orders placed between July 4th, 2023 and July 10th, 2023?'),
//     TextPart('output: {"type": "query", "start": "2023-07-04", "end": "2023-07-10" }'),
//     TextPart('input: List all employee attendance records from August 1st, 2023 to August 31st, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-08-01", "end": "2023-08-31" }'),
//     TextPart('input: Get the number of new users registered between September 1st, 2023 and September 30th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-09-01", "end": "2023-09-30" }'),
//     TextPart('input: Show me the sales figures for the period from October 1st, 2023 to October 31st, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-10-01", "end": "2023-10-31" }'),
//     TextPart('input: Retrieve the customer feedback collected from November 1st, 2023 to November 30th, 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-11-01", "end": "2023-11-30" }'),
//     TextPart('input: Get the website analytics for the month of December 2023.'),
//     TextPart('output: {"type": "query", "start": "2023-12-01", "end": "2023-12-31" }'),
//     TextPart('input: Show me the number of active users on January 1st, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-01-01", "end": "2024-01-01" }'),
//     TextPart('input: What was the total revenue generated between February 1st, 2024 and February 28th, 2024?'),
//     TextPart('output: {"type": "query", "start": "2024-02-01", "end": "2024-02-28" }'),
//     TextPart('input: Get the customer service interactions from March 1st, 2024 to March 31st, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-03-01", "end": "2024-03-31" }'),
//     TextPart('input: Show me the marketing campaign performance for the month of April 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-04-01", "end": "2024-04-30" }'),
//     TextPart('input: Retrieve the product inventory levels between May 1st, 2024 and May 31st, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-05-01", "end": "2024-05-31" }'),
//     TextPart('input: What were the website orders placed from June 1st, 2024 to June 30th, 2024?'),
//     TextPart('output: {"type": "query", "start": "2024-06-01", "end": "2024-06-30" }'),
//     TextPart('input: Get the number of new leads generated between July 1st, 2024 and July 31st, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-07-01", "end": "2024-07-31" }'),
//     TextPart('input: Show me the website traffic data for the month of August 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-08-01", "end": "2024-08-31" }'),
//     TextPart('input: What was the total revenue generated from September 1st, 2024 to September 30th, 2024?'),
//     TextPart('output: {"type": "query", "start": "2024-09-01", "end": "2024-09-30" }'),
//     TextPart('input: Get the customer service interactions between October 1st, 2024 and October 31st, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-10-01", "end": "2024-10-31" }'),
//     TextPart('input: Show me the marketing campaign performance for the month of November 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-11-01", "end": "2024-11-30" }'),
//     TextPart('input: Retrieve the product inventory levels from December 1st, 2024 to December 31st, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-12-01", "end": "2024-12-31" }'),
//     TextPart('input: What were the website orders placed on January 10th, 2024?'),
//     TextPart('output: {"type": "query", "start": "2024-01-10", "end": "2024-01-10" }'),
//     TextPart('input: Get the number of new users registered on February 2nd, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-02-02", "end": "2024-02-02" }'),
//     TextPart('input: Show me the sales figures for March 15th, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-03-15", "end": "2024-03-15" }'),
//     TextPart('input: What was the total revenue generated between July 1st, 2024 and July 15th, 2024?'),
//     TextPart('output: {"type": "query", "start": "2024-07-01", "end": "2024-07-15" }'),
//     TextPart('input: Get the customer service interactions from August 10th, 2024 to August 20th, 2024.'),
//     TextPart('output: {"type": "query", "start": "2024-08-10", "end": "2024-08-20" }'),
//     TextPart('input: Set a reminder for 08:00'),
//     TextPart('output: {"type": "set-time", "time": "08:00" }'),
//     TextPart('input: Remind me at 09:00'),
//     TextPart('output: {"type": "set-time", "time": "9:00" }'),
//     TextPart('input: Set an alarm for 10:00'),
//     TextPart('output: {"type": "set-time", "time": "10:00" }'),
//     TextPart('input: Notify me at 11:00'),
//     TextPart('output: {"type": "set-time", "time": "11:00" }'),
//     TextPart('input: Set a reminder for 12:00'),
//     TextPart('output: {"type": "set-time", "time": "12:00" }'),
//     TextPart('input: Remind me at 13:00'),
//     TextPart('output: {"type": "set-time", "time": "13:00" }'),
//     TextPart('input: Set an alarm for 14:00'),
//     TextPart('output: {"type": "set-time", "time": "14:00" }'),
//     TextPart('input: Notify me at 15:00'),
//     TextPart('output: {"type": "set-time", "time": "15:00" }'),
//     TextPart('input: Set a reminder for 16:00'),
//     TextPart('output: {"type": "set-time", "time": "16:00" }'),
//     TextPart('input: Remind me at 17:00'),
//     TextPart('output: {"type": "set-time", "time": "17:00" }'),
//     TextPart('input: Set an alarm for 18:00'),
//     TextPart('output: {"type": "set-time", "time": "18:00" }'),
//     TextPart('input: Notify me at 19:00'),
//     TextPart('output: {"type": "set-time", "time": "19:00" }'),
//     TextPart('input: Set a reminder for 20:00'),
//     TextPart('output: {"type": "set-time", "time": "20:00" }'),
//     TextPart('input: Remind me at 21:00'),
//     TextPart('output: {"type": "set-time", "time": "21:00" }'),
//     TextPart('input: Set an alarm for 22:00'),
//     TextPart('output: {"type": "set-time", "time": "22:00" }'),
//     TextPart('input: Notify me at 23:00'),
//     TextPart('output: {"type": "set-time", "time": "23:00" }'),
//     TextPart('input: Set a reminder for 00:00'),
//     TextPart('output: {"type": "set-time", "time": "00:00" }'),
//     TextPart('input: Remind me at 01:00'),
//     TextPart('output: {"type": "set-time", "time": "01:00" }'),
//     TextPart('input: Set an alarm for 02:00'),
//     TextPart('output: {"type": "set-time", "time": "02:00" }'),
//     TextPart('input: Notify me at 03:00'),
//     TextPart('output: {"type": "set-time", "time": "03:00" }'),
//     TextPart('input: Set a reminder for 04:00'),
//     TextPart('output: {"type": "set-time", "time": "04:00" }'),
//     TextPart('input: Remind me at 05:00'),
//     TextPart('output: {"type": "set-time", "time": "05:00" }'),
//     TextPart('input: Set an alarm for 06:00'),
//     TextPart('output: {"type": "set-time", "time": "06:00" }'),
//     TextPart('input: Notify me at 07:00'),
//     TextPart('output: {"type": "set-time", "time": "07:00" }'),
//     TextPart('input: Set a reminder for 08:30'),
//     TextPart('output: {"type": "set-time", "time": "08:30" }'),
//     TextPart('input: Add \'Go for a walk\' to my routine every Monday'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "monday": ["Go for a walk"]}]}'),
//     TextPart('input: Remove \'Grocery shopping\' from my Wednesday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "wednesday": ["Grocery shopping"]}]}'),
//     TextPart('input: Add \'Yoga class\' and \'Meal prep\' to my Saturday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "saturday": ["Yoga class", "Meal prep"]}]}'),
//     TextPart('input: Remove \'Clean the house\' and \'Do laundry\' from my Sunday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "sunday": ["Clean the house", "Do laundry"]}]}'),
//     TextPart('input: Add \'Read a book\' to my Tuesday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "tuesday": ["Read a book"]}]}'),
//     TextPart('input: Remove \'Attend a meeting\' from my Thursday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "thursday": ["Attend a meeting"]}]}'),
//     TextPart('input: Add \'Workout\' and \'Cook dinner\' to my Friday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "friday": ["Workout", "Cook dinner"]}]}'),
//     TextPart('input: Remove \'Go to the library\' from my Monday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "monday": ["Go to the library"]}]}'),
//     TextPart('input: Add \'Write a blog post\' to my Wednesday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "wednesday": ["Write a blog post"]}]}'),
//     TextPart('input: Remove \'Catch up with friends\' and \'Go to a concert\' from my Saturday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "saturday": ["Catch up with friends", "Go to a concert"]}]}'),
//     TextPart('input: Add \'Spend time with family\' to my Sunday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "sunday": ["Spend time with family"]}]}'),
//     TextPart('input: Remove \'Go to the gym\' from my Tuesday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "tuesday": ["Go to the gym"]}]}'),
//     TextPart('input: Add \'Learn a new skill\' and \'Prepare for a presentation\' to my Thursday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "thursday": ["Learn a new skill", "Prepare for a presentation"]}]}'),
//     TextPart('input: Remove \'Volunteer at the animal shelter\' from my Friday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "friday": ["Volunteer at the animal shelter"]}]}'),
//     TextPart('input: Add \'Go for a hike\' to my Monday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "monday": ["Go for a hike"]}]}'),
//     TextPart('input: Remove \'Clean the bathroom\' from my Wednesday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "wednesday": ["Clean the bathroom"]}]}'),
//     TextPart('input: Add \'Attend a book club meeting\' and \'Cook a healthy meal\' to my Saturday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "saturday": ["Attend a book club meeting", "Cook a healthy meal"]}]}'),
//     TextPart('input: Remove \'Do laundry\' and \'Pay bills\' from my Sunday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "sunday": ["Do laundry", "Pay bills"]}]}'),
//     TextPart('input: Add \'Practice a musical instrument\' to my Tuesday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "tuesday": ["Practice a musical instrument"]}]}'),
//     TextPart('input: Remove \'Meet with a mentor\' from my Thursday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "thursday": ["Meet with a mentor"]}]}'),
//     TextPart('input: Add \'Go to the movies\' and \'Have dinner with friends\' to my Friday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "friday": ["Go to the movies", "Have dinner with friends"]}]}'),
//     TextPart('input: Remove \'Go to the park\' from my Monday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "monday": ["Go to the park"]}]}'),
//     TextPart('input: Add \'Write a journal entry\' to my Wednesday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add", "wednesday": ["Write a journal entry"]}]}'),
//     TextPart('input: Remove \'Go to a concert\' and \'Have a picnic\' from my Saturday routine'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove", "saturday": ["Go to a concert", "Have a picnic"]}]}'),
//     TextPart('input: I want to add from monday to friday work'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","monday":["work"],"tuesday":["work"],"wednesday":["work"],"thursday":["work"],"friday":["work"]}]}'),
//     TextPart('input: on tuesday and thursday I have gym'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","tuesday":["gym"],"thursday":["gym"]}]}'),
//     TextPart('input: On the weekend I have a volleball match'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","saturday": ["volleball match"],"sunday":["volleball match"] }]}'),
//     TextPart('input: During the whole week I go to work'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","monday":["work"],"tuesday":["work"],"wednesday":["work"],"thursday":["work"],"friday":["work"]}]}'),
//     TextPart('input: During the whole week I go to baseball practice'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","monday":["baseball practice"],"tuesday":["baseball practice"],"wednesday":["baseball practice"],"thursday":["baseball practice"],"friday":["baseball practice"]}]}'),
//     TextPart('input: From monday to wednesday I go dancing'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","monday":["dancing"],"tuesday":["dancing"],"wednesday":["dancing"]}]}'),
//     TextPart('input: I don\'t go anymore to work from monday to friday but from wednesday to sunday'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove","monday":["work"],"tuesday":["work"],"wednesday":["work"],"thursday":["work"],"friday":["work"]},{"kind": "add","wednesday":["work"],"thursday":["work"],"friday":["work"],"saturday":["work"],"sunday":["work"]}]}'),
//     TextPart('input: I don\'t go to frisbee on monday but on tuesday'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove","monday":["frisbee"]},{"kind": "add","tuesday":["frisbee"]}]}'),
//     TextPart('input: I stopped playing volleball'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove","monday":["volleball"],"tuesday":["volleball"],"wednesday":["volleball"],"thursday":["volleball"],"friday":["volleball"],"saturday": ["volleball"],"sunday":["volleball"]}]}'),
//     TextPart('input: I quitted my job'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove","monday":["work"],"tuesday":["work"],"wednesday":["work"],"thursday":["work"],"friday":["work"],"saturday": ["work"],"sunday":["work"] }]}'),
//     TextPart('input: I always do babisitting during the week'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","monday":["babisitting"],"tuesday":["babisitting"],"wednesday":["babisitting"],"thursday":["babisitting"],"friday":["babisitting"]}]}'),
//     TextPart('input: On the weekend I stopped going to the lake'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove","saturday": ["going to the lake"],"sunday":["going to the lake"]}]}'),
//     TextPart('input: I started taking piano lessons on fridays'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","friday":[piano lessons]}]}'),
//     TextPart('input: I stopped taking guitar lessons on thursday and saturday'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove","thursday":["guitar lessons"],"saturday": ["guitar lessons"]}]}'),
//     TextPart('input: Remove the periodic activity for rugby'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "remove","monday":["rugby"],"tuesday":["rugby"],"wednesday":["rugby"],"thursday":["rugby"],"friday":["rugby"],"saturday": ["rugby"],"sunday":["rugby"] }]}'),
//     TextPart('input: Add the periodic activity for taking the dog out during the weekend'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","saturday": ["taking the dog out"],"sunday":["taking the dog out"] }]}'),
//     TextPart('input: On monday and sunday I usually practive swimming'),
//     TextPart('output: {"type": "set-periodicy", "data": [{"kind": "add","monday":["swimming"],"sunday":["swimming"] }]}'),
//     TextPart('input: Hey kali yesterday I went do the cinema with some friends, had dinner and played some videogames'),
//     TextPart('output: '),
//   ]);
//   print(response.text);
// }