// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKzYmFagLb3pPfUoRbrGUKRwrv3lDhs3c',
    appId: '1:473828294205:web:fdd79806cc43694c52f454',
    messagingSenderId: '473828294205',
    projectId: 'khamilia-dev',
    authDomain: 'khamilia-dev.firebaseapp.com',
    storageBucket: 'khamilia-dev.appspot.com',
    measurementId: 'G-D82VRRMCT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMu23E7ThRmJU5WYOHPmzWgFul2lOcOTs',
    appId: '1:473828294205:android:9d63281001c54b6452f454',
    messagingSenderId: '473828294205',
    projectId: 'khamilia-dev',
    storageBucket: 'khamilia-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh00EIYNsRI_G1Drf2CzIH5tM0NttVjZ0',
    appId: '1:473828294205:ios:23d49bb1ec502b2052f454',
    messagingSenderId: '473828294205',
    projectId: 'khamilia-dev',
    storageBucket: 'khamilia-dev.appspot.com',
    androidClientId: '473828294205-b63vv7h2nk0apo59nmhpn1q69onolre6.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh00EIYNsRI_G1Drf2CzIH5tM0NttVjZ0',
    appId: '1:473828294205:ios:23d49bb1ec502b2052f454',
    messagingSenderId: '473828294205',
    projectId: 'khamilia-dev',
    storageBucket: 'khamilia-dev.appspot.com',
    androidClientId: '473828294205-b63vv7h2nk0apo59nmhpn1q69onolre6.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKzYmFagLb3pPfUoRbrGUKRwrv3lDhs3c',
    appId: '1:473828294205:web:86e2785ab711b19f52f454',
    messagingSenderId: '473828294205',
    projectId: 'khamilia-dev',
    authDomain: 'khamilia-dev.firebaseapp.com',
    storageBucket: 'khamilia-dev.appspot.com',
    measurementId: 'G-N8EB0X5JRB',
  );

}